-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  encryption_bindings

CREATE TABLE IF NOT EXISTS encryption_bindings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk VARCHAR(64) NOT NULL,
  field_name VARCHAR(64) NULL,
  field_name_norm VARCHAR(64) GENERATED ALWAYS AS (COALESCE(field_name,'')) STORED,
  key_wrapper_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_enc_bind UNIQUE (entity_table, entity_pk, field_name_norm),
  CONSTRAINT uq_enc_bind_raw UNIQUE (entity_table, entity_pk, field_name)
);
